/-
  The saturation-derived infinite model, in Lean.  UNVERIFIED — this file has never
  been compiled (no Lean in the authoring sandbox).  Run:

      lake env lean paper/lean/OrderedModel.lean

  and expect to fix elaboration errors.  The MATHEMATICS is what is being proposed here,
  and the point of the file is that it isolates exactly one hard obligation.

  ---------------------------------------------------------------------------
  WHAT THIS IS FOR

  `answer_spec.py` fixes the benchmark's two goals:

      AustinGoal  : ∃ (M : Type) (op : M → M → M), (∃ a b : M, a ≠ b) ∧ Law op
      TrivialGoal : ∀ (M : Type) (op : M → M → M), Law op → ∀ a b : M, a = b

  JRS (arXiv:2602.16324) show that a saturated clause set in the unit equational
  fragment IS an explicit, possibly infinite model — via ordered rewriting on ground
  terms.  They lay out the four steps needed to verify such a model (Herbrand domain,
  normalisation function, well-foundedness, confluence), call it "quite involved", and
  do not do it.  ETP is a Lean project.  That gap is this file.

  ---------------------------------------------------------------------------
  THE DECOMPOSITION, AND WHERE THE DIFFICULTY ACTUALLY LIVES

  The Herbrand model is the free algebra on the constants modulo the congruence
  generated by the ground instances of the law.  It satisfies the law *for free* — that
  is `law_holds` below, and it needs no rewriting, no ordering, no confluence.

  Everything hard is NONTRIVIALITY: `⟦c₀⟧ ≠ ⟦c₁⟧`.  And nontriviality reduces cleanly:
  it suffices to exhibit ONE invariant — a function on ground terms that is constant on
  congruence classes and separates the two constants (`nontrivial_of_invariant`).

  The normalisation function of an ordered rewrite system is such an invariant, and it
  is exactly the object `scripts/ordered_model.py` computes.  Its `respects_ax`
  obligation — that both sides of every ground axiom instance have the same normal
  form — IS ground confluence, inherited from saturation under unfailing completion.

  So: this file discharges three of the four steps, and names the fourth.  The remaining
  `sorry` is not a gap in the plan; it is the contribution, stated precisely.

  Note also what is NOT needed: pre-orderedness.  An equation with a free variable on
  each side is used in whichever direction decreases the ground instance (JRS Def. 1).
  That constraint was on their *printer*.  ~36% of our order-5 saturations are not
  plain TRSs, which is why formalising the ordered case — not the pre-ordered case that
  CeTA already certifies — is the contribution worth having.
-/
import Mathlib.Logic.Relation

namespace OrderedModel

variable {C : Type}

/-- Ground terms: one binary operation, constants drawn from `C`. The Herbrand universe. -/
inductive Tm (C : Type) where
  | cst : C → Tm C
  | op : Tm C → Tm C → Tm C
  deriving DecidableEq

/-- A set of ground equations: `E s t` means `s ≈ t` is a ground instance of an axiom.
    For our benchmark, `E` is the set of ground instances of the law `x = T[x,y,z,…]`. -/
abbrev Eqs (C : Type) := Tm C → Tm C → Prop

/-- The congruence generated by `E`. -/
inductive Cong (E : Eqs C) : Tm C → Tm C → Prop
  | ax {s t} : E s t → Cong E s t
  | rfl (t) : Cong E t t
  | symm {s t} : Cong E s t → Cong E t s
  | trans {s t u} : Cong E s t → Cong E t u → Cong E s u
  | cong {a a' b b'} : Cong E a a' → Cong E b b' → Cong E (Tm.op a b) (Tm.op a' b')

theorem Cong.equiv (E : Eqs C) : Equivalence (Cong E) :=
  ⟨Cong.rfl, Cong.symm, Cong.trans⟩

/-- The Herbrand model: ground terms modulo the congruence. -/
def herbrandSetoid (E : Eqs C) : Setoid (Tm C) := ⟨Cong E, Cong.equiv E⟩

def M (E : Eqs C) : Type := Quotient (herbrandSetoid E)

/-- The operation descends to the quotient — this is what `Cong.cong` is for. -/
def opM (E : Eqs C) : M E → M E → M E :=
  Quotient.map₂ Tm.op (fun _ _ h₁ _ _ h₂ => Cong.cong h₁ h₂)

/-! ### Step 1 (free): every axiom holds in the quotient. -/

theorem law_holds (E : Eqs C) {s t : Tm C} (h : E s t) :
    (Quotient.mk (herbrandSetoid E) s) = (Quotient.mk (herbrandSetoid E) t) :=
  Quotient.sound (Cong.ax h)

/-- Every element of the model is the class of some ground term. Needed to discharge the
    universally-quantified law: instantiate at representatives, then use `law_holds`. -/
theorem exists_rep (E : Eqs C) (x : M E) : ∃ t : Tm C, Quotient.mk (herbrandSetoid E) t = x :=
  Quotient.exists_rep x

/-! ### Step 2 (the reduction): nontriviality from a single invariant. -/

/-- An invariant: constant on congruence classes. It suffices that it respects the
    axioms and is compatible with the operation. -/
structure Invariant (E : Eqs C) (β : Type) where
  f : Tm C → β
  respects_ax : ∀ {s t}, E s t → f s = f t
  compat : ∀ {a a' b b'}, f a = f a' → f b = f b' → f (Tm.op a b) = f (Tm.op a' b')

theorem Invariant.respects_cong {E : Eqs C} {β} (I : Invariant E β) :
    ∀ {s t}, Cong E s t → I.f s = I.f t := by
  intro s t h
  induction h with
  | ax h => exact I.respects_ax h
  | rfl _ => rfl
  | symm _ ih => exact ih.symm
  | trans _ _ ih₁ ih₂ => exact ih₁.trans ih₂
  | cong _ _ ih₁ ih₂ => exact I.compat ih₁ ih₂

/-- **The reduction.** A separating invariant makes the Herbrand model nontrivial. -/
theorem nontrivial_of_invariant {E : Eqs C} {β} (I : Invariant E β) {c₀ c₁ : C}
    (hne : I.f (Tm.cst c₀) ≠ I.f (Tm.cst c₁)) :
    (Quotient.mk (herbrandSetoid E) (Tm.cst c₀)) ≠ (Quotient.mk (herbrandSetoid E) (Tm.cst c₁)) := by
  intro h
  exact hne (I.respects_cong (Quotient.exact h))

/-! ### Step 3 (the contribution): the normalisation invariant.

  Let `≻` be a reduction ordering, well-founded on ground terms.  Ordered rewriting:
  rewrite `t[σ l]` to `t[σ r]` whenever `σ l ≻ σ r`, for `l ≈ r` an axiom in either
  direction, with variables free on the far side instantiated to the smallest constant
  (JRS Def. 1).  Termination is immediate from well-foundedness of `≻`.  Define `nf` by
  well-founded recursion.

  The obligation below, `nf (σ l) = nf (σ r)`, is exactly GROUND CONFLUENCE, which is
  inherited from saturation under unfailing completion (Bachmair–Ganzinger; Lynch;
  Peltier).  Formalising *that* is the open work JRS decline.  It is the only thing
  between `scripts/ordered_model.py`'s computation and a Lean theorem.
-/

section Normalisation
variable (E : Eqs C) (gt : Tm C → Tm C → Prop) (hwf : WellFounded gt)

/-- One step of ordered rewriting. `rw s t` iff `t` is obtained from `s` by applying an
    axiom in the decreasing direction at some position. (Stated abstractly here; the
    concrete generator is `ordered_model.py`.) -/
variable (rw : Tm C → Tm C → Prop)

/-- Ordered rewriting only ever decreases, so it terminates. -/
def Decreasing : Prop := ∀ {s t}, rw s t → gt s t

/-- Normal forms exist and are reachable. Follows from `hwf` and `Decreasing`. -/
theorem exists_nf (hdec : Decreasing gt rw) (s : Tm C) :
    ∃ n, Relation.ReflTransGen rw s n ∧ ∀ u, ¬ rw n u := by
  sorry

/-- **THE OPEN OBLIGATION.** Ground confluence of the ordered rewrite system generated
    by a *saturated* set. Everything else in this file is proved. -/
theorem ground_confluent (hsat : True /- placeholder: `E` is saturated -/) :
    ∀ {s t u}, Relation.ReflTransGen rw s t → Relation.ReflTransGen rw s u →
      ∃ v, Relation.ReflTransGen rw t v ∧ Relation.ReflTransGen rw u v := by
  sorry

end Normalisation

/-! ### Step 4: assemble.

  Given a law `L`, take `E := ground instances of L`.  Then

    * `Law (opM E)`      from `law_holds` + `exists_rep`;
    * `⟦c₀⟧ ≠ ⟦c₁⟧`      from `nontrivial_of_invariant` applied to the normalisation
                          invariant, whose `respects_ax` is `ground_confluent`;

  which together are exactly `Problem.AustinGoal` of `answer_spec.py`.  The witness type
  is `M E` and the witness operation is `opM E`.

  Once `ground_confluent` is proved, EVERY CeTA-certified system and every saturation
  our pipeline produces becomes a Lean theorem, mechanically. That is the deliverable.
-/

end OrderedModel
